/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import { describe, it, expect } from 'vitest';
import { decodePly, parsePlyHeader } from './ply.js';

const enc = new TextEncoder();

function buildAsciiPly(rows: Array<[number, number, number]>, withRgb: boolean = false): Uint8Array {
  const props = withRgb
    ? 'property float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\n'
    : 'property float x\nproperty float y\nproperty float z\n';
  const header =
    'ply\n' +
    'format ascii 1.0\n' +
    'comment generated by test\n' +
    `element vertex ${rows.length}\n` +
    props +
    'end_header\n';
  const body = rows.map((r) => withRgb ? `${r[0]} ${r[1]} ${r[2]} 255 128 64` : `${r[0]} ${r[1]} ${r[2]}`).join('\n') + '\n';
  return enc.encode(header + body);
}

function buildBinaryPlyLe(rows: Array<[number, number, number]>, withRgb: boolean = false): Uint8Array {
  const props = withRgb
    ? 'property float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\n'
    : 'property float x\nproperty float y\nproperty float z\n';
  const header =
    'ply\n' +
    'format binary_little_endian 1.0\n' +
    `element vertex ${rows.length}\n` +
    props +
    'end_header\n';
  const headerBytes = enc.encode(header);
  const stride = withRgb ? 15 : 12;
  const body = new ArrayBuffer(rows.length * stride);
  const view = new DataView(body);
  for (let i = 0; i < rows.length; i++) {
    view.setFloat32(i * stride, rows[i][0], true);
    view.setFloat32(i * stride + 4, rows[i][1], true);
    view.setFloat32(i * stride + 8, rows[i][2], true);
    if (withRgb) {
      view.setUint8(i * stride + 12, 255);
      view.setUint8(i * stride + 13, 128);
      view.setUint8(i * stride + 14, 64);
    }
  }
  const merged = new Uint8Array(headerBytes.length + body.byteLength);
  merged.set(headerBytes, 0);
  merged.set(new Uint8Array(body), headerBytes.length);
  return merged;
}

describe('parsePlyHeader', () => {
  it('reads ascii xyz header', () => {
    const buf = buildAsciiPly([[1, 2, 3]]);
    const h = parsePlyHeader(buf);
    expect(h.format).toBe('ascii');
    const v = h.elements.find((e) => e.name === 'vertex')!;
    expect(v.count).toBe(1);
    expect(v.properties.map((p) => p.name)).toEqual(['x', 'y', 'z']);
  });

  it('reads binary_little_endian header with RGB', () => {
    const buf = buildBinaryPlyLe([[0, 0, 0]], true);
    const h = parsePlyHeader(buf);
    expect(h.format).toBe('binary_little_endian');
    const v = h.elements.find((e) => e.name === 'vertex')!;
    expect(v.recordSize).toBe(15);
    expect(v.properties.map((p) => p.name)).toContain('red');
  });

  it('rejects missing magic', () => {
    expect(() => parsePlyHeader(new TextEncoder().encode('not a ply'))).toThrow();
  });
});

describe('decodePly', () => {
  it('decodes ascii xyz', () => {
    const buf = buildAsciiPly([
      [1, 2, 3],
      [-4, -5, -6],
      [10, 20, 30],
    ]);
    const chunk = decodePly(buf);
    expect(chunk.pointCount).toBe(3);
    expect(Array.from(chunk.positions)).toEqual([1, 2, 3, -4, -5, -6, 10, 20, 30]);
    expect(chunk.colors).toBeUndefined();
    expect(chunk.bbox).toEqual({ min: [-4, -5, -6], max: [10, 20, 30] });
  });

  it('decodes ascii xyz + rgb (uchar 0..255)', () => {
    const buf = buildAsciiPly([[1, 1, 1], [2, 2, 2]], true);
    const chunk = decodePly(buf);
    expect(chunk.colors).toBeDefined();
    // Every row uses (255, 128, 64)
    expect(chunk.colors![0]).toBeCloseTo(1.0, 2);
    expect(chunk.colors![1]).toBeCloseTo(128 / 255, 2);
    expect(chunk.colors![2]).toBeCloseTo(64 / 255, 2);
  });

  it('decodes binary little-endian xyz + rgb', () => {
    const buf = buildBinaryPlyLe([[0, 0, 0], [1.5, -2.5, 3.5]], true);
    const chunk = decodePly(buf);
    expect(chunk.pointCount).toBe(2);
    expect(Array.from(chunk.positions.subarray(0, 3))).toEqual([0, 0, 0]);
    expect(Array.from(chunk.positions.subarray(3, 6))).toEqual([1.5, -2.5, 3.5]);
    expect(chunk.colors![0]).toBeCloseTo(1.0, 2);
  });

  it('throws when binary body is short', () => {
    const truncated = buildBinaryPlyLe([[0, 0, 0], [1, 1, 1]], false);
    // chop the last 4 bytes — now we're missing one float of point 2
    const short = truncated.slice(0, truncated.length - 4);
    expect(() => decodePly(short)).toThrow();
  });

  it('rejects a huge declared vertex count backed by a tiny body (no OOM alloc)', () => {
    // Header claims 1e9 vertices but the body is a handful of bytes: without
    // the pre-allocation guard this would attempt a ~12GB Float32Array.
    const header =
      'ply\n' +
      'format binary_little_endian 1.0\n' +
      'element vertex 1000000000\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'end_header\n';
    const buf = enc.encode(header + 'tiny');
    expect(() => decodePly(buf)).toThrow(/body bytes|available/i);
  });

  it('rejects a huge count in an ascii file with a tiny body', () => {
    const header =
      'ply\n' +
      'format ascii 1.0\n' +
      'element vertex 1000000000\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'end_header\n';
    const buf = enc.encode(header + '1 2 3\n');
    expect(() => decodePly(buf)).toThrow(/body bytes|available/i);
  });

  it('ascii body at the minimum byte floor passes (EOF-terminated); truncated fails', () => {
    const header =
      'ply\n' +
      'format ascii 1.0\n' +
      'element vertex 2\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'end_header\n';
    // 2 vertices x 3 properties x 2 bytes ("digit + delimiter") = 12 body
    // bytes with a trailing newline.
    const trailing = decodePly(enc.encode(header + '1 2 3\n4 5 6\n'));
    expect(trailing.pointCount).toBe(2);
    expect(Array.from(trailing.positions)).toEqual([1, 2, 3, 4, 5, 6]);
    // A VALID file whose last record is EOF-terminated (no final newline) is
    // one byte under count*minBytes and must still decode — the floor is
    // count*minBytes - 1.
    const exactEof = decodePly(enc.encode(header + '1 2 3\n4 5 6')); // 11 bytes
    expect(exactEof.pointCount).toBe(2);
    expect(Array.from(exactEof.positions)).toEqual([1, 2, 3, 4, 5, 6]);
    // One byte truncated below the floor: rejected before allocation.
    expect(() => decodePly(enc.encode(header + '1 2 3\n4 5 '))).toThrow(/body bytes|available/i);
  });

  it('rejects a non-integer element count', () => {
    // parseInt would silently truncate "1.5" to 1 and decode garbage.
    const header =
      'ply\n' +
      'format ascii 1.0\n' +
      'element vertex 1.5\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'end_header\n';
    expect(() => decodePly(enc.encode(header + '1 2 3\n'))).toThrow(/invalid element count/);
  });

  it('rejects list-valued properties on the vertex element, allows them on faces', () => {
    // A list on the vertex element makes records variable length: the fixed
    // binary stride / ascii column map would silently drift into garbage.
    const badVertex =
      'ply\n' +
      'format binary_little_endian 1.0\n' +
      'element vertex 1\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'property list uchar int vertex_indices\n' +
      'end_header\n';
    const body = new Uint8Array(32);
    const buf = new Uint8Array(enc.encode(badVertex).length + body.length);
    buf.set(enc.encode(badVertex), 0);
    expect(() => decodePly(buf)).toThrow(/list-valued properties on the vertex element/);

    // Face lists (skipped elements) stay supported.
    const withFaces =
      'ply\n' +
      'format ascii 1.0\n' +
      'element vertex 2\n' +
      'property float x\nproperty float y\nproperty float z\n' +
      'element face 1\n' +
      'property list uchar int vertex_indices\n' +
      'end_header\n';
    const chunk = decodePly(enc.encode(withFaces + '1 2 3\n4 5 6\n2 0 1\n'));
    expect(chunk.pointCount).toBe(2);
    expect(Array.from(chunk.positions)).toEqual([1, 2, 3, 4, 5, 6]);
  });
});
